# syntax=docker/dockerfile:1
# Use Python base image
FROM python:3.12-slim

# Set working directory in the container
WORKDIR /app

# Copy requirements and install (. is the current directory in the container so /app)
RUN apt-get update && apt-get install -y build-essential
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy app code (first . is the current directory in the host, second . is the current directory in the container)
COPY . .

# Expose port and run Flask
EXPOSE 5000
# Default command to run when the container starts
CMD ["python", "app.py"]
# could use CMD ["python3", "-m", "flask", "run", "--host=0.0.0.0"]